### ISSUE TITLE
Option to copy only versioned files if local dir is a git repository

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#10]
### Steps

- Cd to any git repo
- Execute: 
```
touch some_not_versioned_file
rm -rf .compose
plasmactl compose
cd .compose/build/
git status
```

### Current

- `.compose/build/` directory contains `./some_not_versioned_file`

### Expected

- `.compose/build/` directory should not contain `./some_not_versioned_file` but only versioned files of initial current git repository + files of packages listed in compose.yaml if any (similar to a `git checkout-index -a --prefix=".compose/build/"` command)
- This can only work if current directory is a git repository and may not always be expected by user. Therefore it may be relevant to implement it as an option to `compose` command

**Comment by iignatevich** [comment]
added https://github.com/launchrctl/compose/commit/c76f828fea35453b4d1198b1ca630d203a2c54ec
please use -s flag
