### ISSUE TITLE
Compose files conflict verbosity

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#15]
### Observed

When 1 file is in multiple packages (or in local and in a package), would be great to have a warning printed

### Expected

Something like
```
Conflicting files:
- interaction/softwares/roles/rocketchat/templates/Dockerfile.j2 > Selected from package XXX
- interaction/softwares/roles/alfresco_activemq/templates/Dockerfile.j2 > Selected from domain repo
```

### To-do

Implement additional stdout verbosity

**Comment by iignatevich** [comment]
https://github.com/launchrctl/compose/pull/16

**Comment by davidferlay** [comment]
`launchr compose --conflicts-verbosity`
