### ISSUE TITLE
Remove usage of lock file

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#17]
### Observed

In php or yarn/npm world lock file is useful because versions are set "lousely" in main file, like [symfony/routing": "^6.4"](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/composer.json?ref_type=heads#L30) which means "install this package of verson above or equal to 6.4

Then installing it generates lock file where it says : package is installed in version exact: 6.5.2 with that hash etc

It's a mean to ensure reproducibility

### Expected

In case of Compose, packages will be set to either:
- Precise branch name > where we don't want to lock with commit hash but always get latest state of that branch (development phase)
- Tag name > where tag will be exact and it's content not change (release phase)

so it looks like we have no need for lock file

### To-do

- Remove usage of lock file

**Comment by iignatevich** [comment]
https://github.com/launchrctl/compose/pull/18
